### ISSUE TITLE
Crie uma rota que retorne o local do evento através do nome do evento

### ISSUE THREAD

**Issue by joaopblume** [clovisdanielcosta/python-agenda#5]
Seu código funcionou para esse exercício? Pois no meu não funcionou ...

**Comment by clovisdanielcosta** [comment]
Olá amigo. Desculpa. Só pude olhar agora. Meu projetinho tá rodando no Heroku com pipeline automático do GitHub. Dá uma olhada:

https://python-agenda.herokuapp.com/

**Comment by clovisdanielcosta** [comment]
O usuário é "convidado" e a senha é "user12345" como está no meu README.md
